const menuByRole={
 admin:[['dashboard','⌂','ภาพรวมวันนี้'],['employees','♙','พนักงาน'],['offices','◇','Office / Branch'],['schedule','□','ตารางงาน'],['attendance','◷','แก้ไขเวลา'],['clock-approvals','✓','คำขอลงเวลา'],['leave','✈','การลา'],['reports','▤','รายงาน'],['line','◉','LINE Report'],['audit','≋','Audit Log'],['settings','⚙','ตั้งค่าระบบ']],
 hr:[['dashboard','⌂','ภาพรวมวันนี้'],['employees','♙','พนักงาน'],['schedule','□','ตารางงาน'],['clock-approvals','✓','คำขอลงเวลา'],['leave','✈','การลา'],['reports','▤','รายงาน'],['hr-settings','⚙','ตั้งค่า HR']],
 employee:[['clock','◷','ลงเวลา'],['clock-request','＋','ขอลงเวลา'],['calendar','□','ปฏิทิน'],['my-leave','✈','การลา']],
 ba:[['clock','◷','ลงเวลา'],['clock-request','＋','ขอลงเวลา'],['calendar','□','ปฏิทินสาขา'],['my-leave','✈','การลา']],
 driver:[['clock','◷','ลงเวลา'],['clock-request','＋','ขอลงเวลา'],['calendar','□','ปฏิทิน'],['my-leave','✈','การลา']]
};
const titles={dashboard:['WORKFORCE OVERVIEW','ภาพรวมวันนี้'],employees:['PEOPLE DIRECTORY','พนักงาน'],offices:['WORKPLACE MANAGEMENT','Office / Branch'],schedule:['WORK SCHEDULE','ตารางงาน'],attendance:['ATTENDANCE OPERATION','แก้ไขเวลา'],leave:['LEAVE MANAGEMENT','การลา'],reports:['REPORT CENTER','รายงาน'],line:['LINE OPERATIONS','LINE Report'],audit:['SECURITY & TRACEABILITY','Audit Log'],settings:['SYSTEM CONTROL','ตั้งค่าระบบ'],'hr-settings':['HR PREFERENCES','ตั้งค่า HR'],team:['MY TEAM','ทีมของฉัน'],clock:['TIME ATTENDANCE','ลงเวลา'],calendar:['MY CALENDAR','ปฏิทิน'],'my-leave':['MY LEAVE','การลาของฉัน'],'clock-request':['ATTENDANCE REQUEST','ขอลงเวลา'],'clock-approvals':['ATTENDANCE APPROVALS','คำขอลงเวลา'],more:['','จัดการ']};
let state={role:'admin',page:'dashboard',hrView:'work'};
let selectedScheduleDay=8;
let personalCalendar={year:2026,month:8,day:8};
const $=s=>document.querySelector(s);
const LIVE_CONFIG={
 LIFF_ID:'2010336238-Ub6d565R',
 API_URL:'https://rlqecfzddxpywbbbiirg.supabase.co/functions/v1/rapid-processor-staging',
 TIMEOUT:15000
};
let live={connected:false,bootstrap:null,employees:[],offices:[],daily:null,today:null};
function bkkDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
async function liveApi(action,payload={}){
 const token=liff.getAccessToken();if(!token)throw new Error('กรุณาเปิดผ่าน LINE เพื่ออ่านข้อมูลจริง');
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),LIVE_CONFIG.TIMEOUT);
 try{const response=await fetch(`${LIVE_CONFIG.API_URL}?action=${encodeURIComponent(action)}`,{method:'POST',headers:{'Content-Type':'application/json','x-line-access-token':token},body:JSON.stringify(payload),signal:controller.signal});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.message||data.error||`HTTP ${response.status}`);return data}finally{clearTimeout(timer)}
}
function liveRole(boot){
 const adminRole=String(boot.adminRole||'').toUpperCase();
 if(adminRole==='HR')return 'hr';
 if(boot.isAdmin)return 'admin';
 const mode=String(boot.employee?.attendance_mode||'STANDARD').toUpperCase();
 if(mode==='MULTI_BRANCH')return 'ba';if(mode==='DRIVER')return 'driver';return 'employee';
}
async function initLive(){
 const status=$('#environmentStatus');
 try{
  await liff.init({liffId:LIVE_CONFIG.LIFF_ID});
  if(!liff.isLoggedIn()){status.textContent='STAGING · เปิดผ่าน LINE เพื่อดูข้อมูลจริง';return}
  live.bootstrap=await liveApi('bootstrap');live.connected=true;document.body.classList.add('live-readonly');
  const role=liveRole(live.bootstrap);$('#roleSelect').value=role;setRole(role);
  if(live.bootstrap.employee)live.today=await liveApi('today',{date:bkkDate()});
  if(live.bootstrap.isAdmin){const [directory,daily]=await Promise.all([liveApi('admin_bootstrap'),liveApi('admin_daily',{date:bkkDate()})]);live.employees=directory.employees||[];live.offices=directory.offices||[];live.daily=daily;}
  status.textContent='STAGING · ข้อมูลจริงแบบอ่านอย่างเดียว';renderPage();
 }catch(error){status.textContent=`STAGING · ${error.message||error}`;status.classList.add('connection-error')}
}

function renderNav(){
 const items=['admin','hr'].includes(state.role)&&state.hrView==='personal'?menuByRole.employee:menuByRole[state.role];
 const html=items.map(([id,icon,label])=>`<button class="nav-item ${state.page===id?'active':''}" data-page="${id}"><span class="nav-icon">${icon}</span><span>${label}</span></button>`).join('');
 $('#desktopNav').innerHTML=html;
 const mobile=['admin','hr'].includes(state.role)&&state.hrView!=='personal'
  ? (state.role==='admin'
    ? [['dashboard','⌂','วันนี้'],['employees','♙','พนักงาน'],['schedule','□','ตาราง'],['reports','▤','รายงาน'],['more','•••','จัดการ']]
    : [['dashboard','⌂','วันนี้'],['employees','♙','พนักงาน'],['schedule','□','ตาราง'],['reports','▤','รายงาน'],['more','•••','จัดการ']])
  : items;
 $('#bottomNav').innerHTML=mobile.map(([id,icon,label])=>`<button class="nav-item ${state.page===id?'active':''}" data-page="${id}"><span class="nav-icon">${icon}</span><span>${label.replace('ภาพรวมวันนี้','วันนี้')}</span></button>`).join('');
 document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));
}
function go(page){
 const currentMenu=['admin','hr'].includes(state.role)&&state.hrView==='personal'?menuByRole.employee:menuByRole[state.role];
 const allowed=currentMenu.some(x=>x[0]===page)||(['admin','hr'].includes(state.role)&&state.hrView!=='personal'&&page==='more'); state.page=allowed?page:(['admin','hr'].includes(state.role)&&state.hrView==='personal'?'clock':'dashboard');
 const [,title]=titles[state.page]; $('#pageTitle').textContent=title;
 renderNav();renderPage();$('.sidebar').classList.remove('open');
}
const stats=[['เข้างานแล้ว','11','จาก 17 คน','✓','green'],['ยังไม่เข้างาน','4','ควรเข้างานวันนี้','!','red'],['กำลังพัก','2','ออกพักอยู่ขณะนี้','◷','amber'],['ลา / WFH','4','ลา 3 · WFH 1','⌂','blue']];
function dashboard(){return `<div class="hero"><div><p class="eyebrow" style="color:#cbd3e2">GOOD AFTERNOON</p><h2>ทีมวันนี้เป็นอย่างไรบ้าง</h2><p>ข้อมูลสาธิตสำหรับตรวจหน้าตาและสิทธิ์การใช้งาน</p></div><div class="date-badge"><strong>8 กันยายน 2569</strong><br><small>วันอังคาร · Bangkok</small></div></div><div class="stats">${stats.map(s=>`<article class="stat-card"><div class="stat-top"><span>${s[0]}</span><span class="status-icon ${s[4]}">${s[3]}</span></div><strong>${s[1]}</strong><small>${s[2]}</small></article>`).join('')}</div><div class="grid-2"><section class="panel"><div class="panel-header"><div><h2>ความเคลื่อนไหวล่าสุด</h2><span class="panel-sub">อัปเดตล่าสุด 13:55 น.</span></div><button class="text-btn">ดูทั้งหมด</button></div><div class="activity">${[['13:42','HO018 · Don','เข้างาน · Head Office','green'],['13:10','BA012 · Mew','เริ่มงาน · Siam Paragon','blue'],['12:58','HO021 · Nan','เข้าพัก','amber'],['09:17','HO007 · Ploy','เข้างาน · Head Office','green']].map(x=>`<div class="activity-row"><span class="time">${x[0]}</span><span class="status-icon ${x[3]}">●</span><div><strong>${x[1]}</strong><small>${x[2]}</small></div></div>`).join('')}</div></section><section class="panel"><div class="panel-header"><div><h2>สถานะทีม</h2><span class="panel-sub">แบ่งตามรูปแบบการทำงาน</span></div></div>${[['Head Office','8 / 11','72%'],['BA','4 / 5','80%'],['Driver','1 / 1','100%']].map(x=>`<div style="margin:18px 0"><div style="display:flex;justify-content:space-between"><strong>${x[0]}</strong><span>${x[1]}</span></div><div style="height:7px;background:#edf0f4;border-radius:9px;margin-top:8px"><div style="height:100%;width:${x[2]};background:var(--pink);border-radius:9px"></div></div></div>`).join('')}</section></div>`}
function employees(){const people=[['HO001','Shane Kitty','Administrator · Head Office','SK','อาทิตย์'],['HO018','Don Thanakorn','Employee · Head Office','DT','เสาร์, อาทิตย์'],['BA012','Mew Arisa','BA · Siam Paragon','MA','ตามตาราง'],['DR001','Ton Nattapong','Driver · Head Office','TN','ตามการลงเวลา']];return `<div class="page-intro"><div><h2>รายชื่อพนักงาน</h2><p>จัดการข้อมูลพื้นฐานและวันหยุดประจำสัปดาห์</p></div><button class="btn pink" id="addEmployee">+ เพิ่มพนักงาน</button></div><section class="panel"><div class="filters"><input placeholder="ค้นหาชื่อหรือรหัสพนักงาน"><select><option>ทุกสถานะ</option><option>Active</option><option>Inactive</option></select><select><option>ทุกสำนักงาน</option><option>Head Office</option></select></div><div class="employee-list">${people.map(p=>`<div class="employee-row"><span class="avatar">${p[3]}</span><div><strong>${p[0]} · ${p[1]}</strong><small>${p[2]} · วันหยุด: ${p[4]}</small></div><span class="tag green">Active</span><div class="actions"><button class="btn secondary">ดูข้อมูล</button><button class="btn primary">แก้ไข</button></div></div>`).join('')}</div></section>`}
function schedule(){let days=[];for(let i=0;i<35;i++){let n=i-1;days.push(n<1||n>30?`<div></div>`:`<div class="cal-day ${[5,6,12,13,19,20,26,27].includes(n)?'off':''} ${n===8?'today':''}"><strong>${n}</strong><span class="dot"></span></div>`)}return `<div class="page-intro"><div><h2>กันยายน 2569</h2><p>ตารางรวม · แสดงข้อมูลตัวอย่างเท่านั้น</p></div><div><button class="btn secondary">สร้างเดือนหน้า</button> <button class="btn primary">แก้ไขตาราง</button></div></div><div class="grid-2"><section class="panel"><div class="calendar">${['อา','จ','อ','พ','พฤ','ศ','ส'].map(x=>`<div class="cal-head">${x}</div>`).join('')}${days.join('')}</div></section><section class="panel"><h2>อังคาร 8 ก.ย.</h2><p class="panel-sub">17 คนมีตารางงาน</p>${[['WORK','11 คน','green'],['OFF','2 คน','red'],['WFH','1 คน','blue'],['LEAVE','3 คน','amber']].map(x=>`<div class="activity-row"><span class="status-icon ${x[2]}">●</span><div><strong>${x[0]}</strong><small>${x[1]}</small></div></div>`).join('')}</section></div>`}
function interactiveSchedule(){const isHR=state.role==='hr';const allPeople=[['HO001','Shane Kitty','Head Office'],['HO018','Don Thanakorn','Head Office'],['HO021','Nan Nicha','Head Office'],['HO007','Ploy Kanya','Head Office'],['BA012','Mew Arisa','Siam Paragon'],['DR001','Ton Nattapong','Driver Route']];const people=isHR?allPeople.filter(p=>p[0].startsWith('HO')):allPeople;const statuses=['WORK','WORK','WFH','LEAVE','WORK','OFF'];let days=[];for(let i=0;i<35;i++){const n=i-1;days.push(n<1||n>30?'<div></div>':`<button class="cal-day cal-button ${[5,6,12,13,19,20,26,27].includes(n)?'off':''} ${n===selectedScheduleDay?'selected':''}" data-schedule-day="${n}"><strong>${n}</strong><span class="dot"></span></button>`)}const rows=people.map((p,i)=>{let status=statuses[allPeople.findIndex(x=>x[0]===p[0])];if(selectedScheduleDay%7===6||selectedScheduleDay%7===0)status=p[0]==='BA012'?'WORK':'OFF';const cls={WORK:'green',OFF:'red',WFH:'blue',LEAVE:'amber'}[status];return `<div class="schedule-person"><span class="avatar">${p[1].split(' ').map(x=>x[0]).join('').slice(0,2)}</span><div><strong>${p[0]} · ${p[1]}</strong><small>${p[2]} · ${status==='WORK'?'09:00–18:00':'ไม่มีเวลาทำงาน'}</small></div><span class="tag ${cls}">${status}</span><button class="text-btn">ดูรายละเอียด</button></div>`}).join('');return `<div class="page-intro"><div><h2>กันยายน 2569</h2><p>${isHR?'Head Office เท่านั้น · กดวันที่เพื่อดูรายชื่อ':'กดวันที่เพื่อดูตารางพนักงาน'}</p></div><div><button class="btn secondary preview-action">สร้างเดือนหน้า</button> <button class="btn primary preview-action">แก้ไขตาราง</button></div></div><div class="schedule-layout"><section class="panel"><div class="calendar">${['อา','จ','อ','พ','พฤ','ศ','ส'].map(x=>`<div class="cal-head">${x}</div>`).join('')}${days.join('')}</div></section><section class="panel schedule-details"><div class="panel-header"><div><p class="eyebrow">SELECTED DATE</p><h2>${selectedScheduleDay} กันยายน 2569</h2></div><span class="tag">${people.length} คน</span></div><div class="schedule-legend"><span><i class="green"></i>WORK</span><span><i class="red"></i>OFF</span><span><i class="blue"></i>WFH</span><span><i class="amber"></i>LEAVE</span></div><div class="employee-list">${rows}</div></section></div>`}
function leave(){return `<div class="page-intro"><div><h2>คำขอลา</h2><p>ตรวจสอบ อนุมัติ และบันทึกลาแทนพนักงาน</p></div><button class="btn pink">+ บันทึกการลา</button></div><section class="panel"><div class="tabs"><button class="tab active">รออนุมัติ · 2</button><button class="tab">อนุมัติแล้ว</button><button class="tab">ไม่อนุมัติ</button><button class="tab">ทั้งหมด</button></div>${[['09','HO021 · Nan','ลาป่วย · 1 วัน','รออนุมัติ'],['12','HO007 · Ploy','ลากิจ · 0.5 วัน','รออนุมัติ']].map(x=>`<div class="leave-card"><div class="leave-date">${x[0]}<small>ก.ย.</small></div><div><strong>${x[1]}</strong><p>${x[2]}</p></div><span class="tag amber">${x[3]}</span><button class="btn primary">ตรวจสอบ</button></div>`).join('')}</section>`}
function reports(){const data=[['▦','รายงานรายวัน','สรุปเวลาและสถานะพนักงานประจำวัน'],['▤','รายงานรายเดือน','ภาพรวมชั่วโมงทำงานและการลา'],['♙','รายงานรายบุคคล','ประวัติ Attendance ของพนักงาน'],['◫','A4 / PNG','สร้างรายงานพร้อมพิมพ์'],['◎','ภาพรวมองค์กร',state.role==='hr'?'ข้อมูล Head Office เท่านั้น':'เปรียบเทียบสถานะตามสิทธิ์']];return `<div class="page-intro"><div><h2>ศูนย์รายงาน</h2><p>${state.role==='hr'?'Head Office เท่านั้น · ไม่มี Export Excel':'เลือกประเภทและช่วงเวลาที่ต้องการ · ไม่มี Export Excel'}</p></div></div><div class="report-grid">${data.map(x=>`<article class="report-card"><span>${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p><button class="text-btn">เปิดรายงาน →</button></article>`).join('')}</div>`}
function hrDashboard(){const hstats=[['เข้างานแล้ว','8','จาก 11 คน Head Office','✓','green'],['ยังไม่เข้างาน','2','Head Office เท่านั้น','!','red'],['กำลังพัก','1','Head Office เท่านั้น','◷','amber'],['ลา / WFH','2','ลา 1 · WFH 1','⌂','blue']];return `<div class="hero"><div><p class="eyebrow" style="color:#cbd3e2">HEAD OFFICE OVERVIEW</p><h2>ภาพรวม Head Office</h2><p>HR ไม่สามารถดูข้อมูล BA และ Driver</p></div><div class="date-badge"><strong>8 กันยายน 2569</strong><br><small>วันอังคาร · Bangkok</small></div></div><div class="stats">${hstats.map(s=>`<article class="stat-card"><div class="stat-top"><span>${s[0]}</span><span class="status-icon ${s[4]}">${s[3]}</span></div><strong>${s[1]}</strong><small>${s[2]}</small></article>`).join('')}</div><div class="grid-2"><section class="panel"><h2>ความเคลื่อนไหว Head Office</h2>${[['13:42','HO018 · Don','เข้างาน · Head Office','green'],['12:58','HO021 · Nan','เข้าพัก · Head Office','amber'],['09:17','HO007 · Ploy','เข้างาน · Head Office','green']].map(x=>`<div class="activity-row"><span class="time">${x[0]}</span><span class="status-icon ${x[3]}">●</span><div><strong>${x[1]}</strong><small>${x[2]}</small></div></div>`).join('')}</section><section class="panel"><div class="restricted"><strong>HEAD OFFICE ONLY</strong><p>BA และ Driver ถูกซ่อนทั้ง Dashboard, รายชื่อ, ตาราง, การลา และรายงาน</p></div></section></div>`}
function hrEmployees(){const people=[['HO001','Shane Kitty','Administrator · Head Office','SK','อาทิตย์'],['HO018','Don Thanakorn','Employee · Head Office','DT','เสาร์, อาทิตย์'],['HO021','Nan Nicha','Employee · Head Office','NN','เสาร์, อาทิตย์']];return `<div class="page-intro"><div><h2>พนักงาน Head Office</h2><p>ไม่รวม BA และ Driver</p></div><button class="btn pink" id="addEmployee">+ เพิ่มพนักงาน</button></div><section class="panel"><div class="filters"><input placeholder="ค้นหาชื่อหรือรหัส HO"><select disabled><option>Head Office เท่านั้น</option></select></div>${people.map(p=>`<div class="employee-row"><span class="avatar">${p[3]}</span><div><strong>${p[0]} · ${p[1]}</strong><small>${p[2]} · วันหยุด: ${p[4]}</small></div><span class="tag green">Active</span><button class="btn primary">แก้ไข</button></div>`).join('')}</section>`}
function clock(){const ba=state.role==='ba',driver=state.role==='driver';return `<div class="clock-view"><section class="panel clock-card"><p class="eyebrow">เวลาปัจจุบัน</p><div class="big-time">13:55</div><p class="panel-sub">วันอังคาร, 8 กันยายน 2569</p><div class="clock-status"><span class="status-icon green">✓</span><div><strong>${ba?'สาขา Siam Paragon':driver?'พร้อมเริ่มงาน':'Head Office'}</strong><small>${ba?'เลือกสาขาก่อนลงเวลา':driver?'Driver Route · พิกัดพร้อม':'ระยะห่าง 34 เมตร · พิกัดพร้อม'}</small></div></div>${ba?'<label class="branch-select">สาขาที่ปฏิบัติงาน<select><option>Siam Paragon</option><option>Central World</option></select></label>':''}<div class="clock-actions">${driver?'<button class="btn primary">เข้างาน</button><button class="btn secondary">ออกพัก</button><button class="btn secondary">เข้าพัก</button><button class="btn pink">ออกงาน</button>':'<button class="btn primary">เข้างาน</button><button class="btn pink">ออกงาน</button>'}</div><p class="logic-note">Preview เท่านั้น — ไม่เปลี่ยน logic ${ba?'BA':driver?'Driver':'ลงเวลา'} เดิม</p></section></div>`}
function personalCalendarView(){const thaiMonths=['มกราคม','กุมภาพันธ์','มีนาคม','เมษายน','พฤษภาคม','มิถุนายน','กรกฎาคม','สิงหาคม','กันยายน','ตุลาคม','พฤศจิกายน','ธันวาคม'];const first=new Date(personalCalendar.year,personalCalendar.month,1).getDay();const total=new Date(personalCalendar.year,personalCalendar.month+1,0).getDate();const owner={admin:'HO001 · Shane Kitty',hr:'HO005 · Pim HR',employee:'HO018 · Don Thanakorn',ba:'BA012 · Mew Arisa',driver:'DR001 · Ton Nattapong'}[state.role];let cells=Array(first).fill('<div></div>');for(let day=1;day<=total;day++){const weekend=new Date(personalCalendar.year,personalCalendar.month,day).getDay()===0;const hasClock=!weekend&&day<=8;cells.push(`<button class="cal-day cal-button personal-day ${day===personalCalendar.day?'selected':''}" data-personal-day="${day}"><strong>${day}</strong>${hasClock?'<span class="dot"></span>':weekend?'<span class="dot off-dot"></span>':''}</button>`)}const hasData=personalCalendar.day<=8&&new Date(personalCalendar.year,personalCalendar.month,personalCalendar.day).getDay()!==0;return `<div class="page-intro"><div><h2>ปฏิทินของฉัน</h2><p>${owner} · เห็นเฉพาะการลงเวลาของบัญชีนี้</p></div></div><div class="personal-calendar-layout"><section class="panel"><div class="month-nav"><button class="icon-button" data-month-shift="-1" aria-label="เดือนก่อนหน้า">‹</button><h2>${thaiMonths[personalCalendar.month]} ${personalCalendar.year+543}</h2><button class="icon-button" data-month-shift="1" aria-label="เดือนถัดไป">›</button></div><div class="calendar">${['อา','จ','อ','พ','พฤ','ศ','ส'].map(x=>`<div class="cal-head">${x}</div>`).join('')}${cells.join('')}</div><div class="calendar-key"><span><i class="worked"></i>มีการลงเวลา</span><span><i class="no-work"></i>ไม่มีการลงเวลา</span></div></section><section class="panel personal-day-detail"><p class="eyebrow">MY ATTENDANCE</p><h2>${personalCalendar.day} ${thaiMonths[personalCalendar.month]} ${personalCalendar.year+543}</h2>${hasData?`<div class="personal-timeline"><div><span>เข้างาน</span><strong>09:02</strong></div><div><span>ออกพัก</span><strong>12:10</strong></div><div><span>เข้าพัก</span><strong>13:01</strong></div><div><span>ออกงาน</span><strong>18:08</strong></div></div><div class="worked-summary"><span class="status-icon green">✓</span><div><strong>ลงเวลาครบ</strong><small>เวลาทำงานรวม 8 ชม. 06 นาที</small></div></div>`:'<div class="empty-day"><strong>ไม่มีข้อมูลการลงเวลา</strong><p>วันนี้ไม่มีเหตุการณ์ลงเวลาของคุณ</p></div>'}</section></div>`}
function calendar(){return personalCalendarView()}
function myLeave(){return leave()}
function lineReport(){return `<div class="page-intro"><div><h2>LINE Report</h2><p>ตรวจสอบรายงานก่อนส่ง · Admin เท่านั้น</p></div><span class="tag green">CRON ACTIVE</span></div><div class="line-grid"><section class="panel"><div class="panel-header"><div><p class="eyebrow">MIDDAY REPORT</p><h2>รายงาน 13:00</h2></div><span class="tag green">ส่งแล้ว 13:00</span></div><div class="line-preview"><strong>Kitty Attendance · 8 ก.ย. 2569</strong><p>✅ เข้างานแล้ว 11 คน</p><p>❌ ยังไม่เข้างาน 4 คน</p><p>☕ กำลังพัก 2 คน</p><p>📝 ลา 3 คน · WFH 1 คน</p></div><div class="report-actions"><button class="btn secondary preview-action">ดูตัวอย่าง</button><button class="btn pink preview-action">Send Now</button></div></section><section class="panel"><div class="panel-header"><div><p class="eyebrow">END OF DAY REPORT</p><h2>รายงาน 22:00</h2></div><span class="tag amber">รอส่ง</span></div><div class="line-preview"><strong>สรุปสิ้นวัน</strong><p>ชั่วโมงทำงานและเวลาออกงาน</p><p>รายการผิดปกติ / ลืมออกงาน</p><p>สรุป BA และ Driver ตามกฎเดิม</p></div><div class="report-actions"><button class="btn secondary preview-action">ดูตัวอย่าง</button><button class="btn pink preview-action">Send Now</button></div></section></div><div class="grid-2 line-lower"><section class="panel"><div class="panel-header"><h2>ตรวจความพร้อม</h2><span class="tag green">พร้อม</span></div>${[['Schedule วันนี้ครบ','17 / 17','green'],['Daily Summary คำนวณแล้ว','17 / 17','green'],['WORK แต่ยังไม่ IN','4 คน','red'],['Inactive ติดรายงาน','0 คน','green']].map(x=>`<div class="activity-row"><span class="status-icon ${x[2]}">${x[2]==='red'?'!':'✓'}</span><div><strong>${x[0]}</strong><small>${x[1]}</small></div></div>`).join('')}</section><section class="panel"><div class="panel-header"><h2>ผู้รับรายงาน</h2><button class="text-btn preview-action">จัดการ</button></div>${[['SK','Shane Kitty','Admin'],['PK','Pim Kitty','Owner']].map(x=>`<div class="employee-row"><span class="avatar">${x[0]}</span><div><strong>${x[1]}</strong><small>${x[2]} · รับรายงาน 13:00 และ 22:00</small></div><span class="tag green">Active</span></div>`).join('')}<p class="logic-note">หน้านี้เป็น UI Preview เท่านั้น ไม่เรียก LINE API และไม่เปลี่ยน logic รายงานเดิม</p></section></div>`}
function clockRequest(){return `<div class="page-intro"><div><h2>ขอลงเวลาย้อนหลัง</h2><p>สำหรับเหตุการณ์ที่ลืมลงเวลา · ส่งให้ HR หรือ Admin อนุมัติ</p></div><span class="tag amber">ใช้แล้ว 2 / 2 ครั้งในเดือนนี้</span></div><div class="grid-2"><section class="panel request-form"><div class="quota-strip danger"><div><strong>คำขอครั้งถัดไปจะเป็นครั้งที่ 3</strong><small>ยังส่งคำขอได้ แต่ระบบจะบันทึกเป็นสีแดงว่าเกิดบ่อย</small></div><strong>ครั้งที่ 3</strong></div><label>วันที่เกิดเหตุ<input type="date" value="2026-09-08"></label><label>เหตุการณ์ที่ลืม<select><option>เข้างาน</option><option>ออกงาน</option><option>ออกพัก</option><option>เข้าพัก</option></select></label><label>เวลาที่ต้องการขอแก้<input type="time" value="09:00"></label><label>เหตุผล<textarea rows="4" placeholder="อธิบายเหตุผลที่ลืมลงเวลา"></textarea></label><button class="btn pink request-submit">ส่งคำขออนุมัติ</button><p class="logic-note">การส่งคำขอไม่แก้ Attendance ทันที ต้องรอ HR หรือ Admin อนุมัติก่อน</p></section><section class="panel"><div class="panel-header"><div><h2>ประวัติเดือนกันยายน</h2><span class="panel-sub">นับตามเดือนปฏิทิน</span></div></div>${[['3 ก.ย.','ลืมเข้างาน · 09:04','อนุมัติแล้ว','green','ครั้งที่ 1'],['6 ก.ย.','ลืมออกงาน · 18:12','อนุมัติแล้ว','green','ครั้งที่ 2'],['8 ก.ย.','คำขอใหม่','เกินสิทธิ์ปกติ','red','ครั้งที่ 3']].map(x=>`<div class="request-history ${x[3]==='red'?'frequent':''}"><div><strong>${x[0]} · ${x[1]}</strong><small>${x[4]} · ${x[2]}</small></div><span class="tag ${x[3]}">${x[3]==='red'?'เกิดบ่อย':'ปกติ'}</span></div>`).join('')}</section></div>`}
function clockApprovals(){let rows=[['HO018','Don Thanakorn','ลืมเข้างาน · 8 ก.ย. 09:00','ครั้งที่ 3 เดือนนี้','red'],['HO021','Nan Nicha','ลืมออกงาน · 7 ก.ย. 18:10','ครั้งที่ 1 เดือนนี้','green'],['BA012','Mew Arisa','ลืมเลือกสาขา · 7 ก.ย. 10:05','ครั้งที่ 4 เดือนนี้','red'],['DR001','Ton Nattapong','ลืมเข้าพัก · 6 ก.ย. 13:00','ครั้งที่ 2 เดือนนี้','amber']];if(state.role==='hr')rows=rows.filter(x=>x[0].startsWith('HO'));return `<div class="page-intro"><div><h2>คำขอลงเวลารออนุมัติ</h2><p>${state.role==='hr'?'เฉพาะ Head Office · ไม่เห็น BA และ Driver':'ทุกกลุ่มพนักงาน'}</p></div><span class="tag">${rows.length} รายการ</span></div><section class="panel"><div class="tabs"><button class="tab active">รออนุมัติ</button><button class="tab">อนุมัติแล้ว</button><button class="tab">ไม่อนุมัติ</button><button class="tab">ทั้งหมด</button></div>${rows.map(x=>`<div class="approval-row ${x[4]==='red'?'frequent':''}"><span class="avatar">${x[0].slice(0,2)}</span><div><strong>${x[0]} · ${x[1]}</strong><small>${x[2]} · ${x[3]}</small></div><span class="tag ${x[4]}">${x[4]==='red'?'เกิดบ่อย':''}</span><button class="btn secondary approval-action">ไม่อนุมัติ</button><button class="btn primary approval-action">อนุมัติ</button></div>`).join('')}<p class="logic-note">เมื่อ HR หรือ Admin อนุมัติ ระบบจริงจึงค่อยเรียก service แก้ Attendance, บันทึกผู้อนุมัติและ Audit Log</p></section>`}
function adminOnly(){return `<section class="panel"><div class="panel-header"><div><h2>${titles[state.page][1]}</h2><span class="panel-sub">คงจุดเชื่อมต่อกับฟังก์ชัน Admin เดิม</span></div><span class="tag">ADMIN ONLY</span></div><p>หน้าตัวอย่างนี้สงวนเมนูไว้สำหรับ Admin และไม่ได้เรียก API หรือเปลี่ยน logic หลังบ้าน</p>${state.page==='audit'?`<div class="activity"><div class="activity-row"><span class="time">14:22</span><span class="status-icon blue">≋</span><div><strong>Admin แก้เวลาออกงาน HO018</strong><small>เหตุผล: ลืมกดออกงาน · Preview data</small></div></div></div>`:''}</section>`}
function hrSettings(){return `<section class="panel"><h2>ตั้งค่า HR</h2><p class="panel-sub">เฉพาะค่าการแสดงผลและงานบุคคลทั่วไป</p><div class="restricted"><div style="font-size:34px">◉</div><h2>การตั้งค่าระบบสำคัญถูกซ่อน</h2><p>HR ไม่สามารถดู Audit Log, ตั้งค่า Role สำคัญ, ผู้รับ LINE Report หรือสั่ง Send Now</p></div></section>`}
function esc(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function employeeDirectory(){
 if(!live.connected||!live.employees.length)return state.role==='hr'?hrEmployees():employees();
 const source=state.role==='hr'?live.employees.filter(person=>String(person.employee_code||'').startsWith('HO')):live.employees;
 const rows=source.map(person=>{const code=esc(person.employee_code),name=esc(person.name),mode=esc(person.attendance_mode||'STANDARD'),initials=esc(String(person.name||person.employee_code||'--').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase());return `<div class="employee-row"><span class="avatar">${initials}</span><div><strong>${code} · ${name}</strong><small>${mode}</small></div><span class="tag ${person.active?'green':'red'}">${person.active?'Active':'Inactive'}</span><button class="btn secondary">ดูข้อมูล</button></div>`}).join('');
 return `<div class="page-intro"><div><h2>${state.role==='hr'?'พนักงาน Head Office':'รายชื่อพนักงาน'}</h2></div></div><section class="panel"><div class="filters"><input placeholder="ค้นหาชื่อหรือรหัสพนักงาน" disabled><span class="tag green">ข้อมูลจริง · อ่านอย่างเดียว</span></div><div class="employee-list">${rows||'<p>ไม่พบพนักงาน</p>'}</div></section>`;
}
function connectedDashboard(){
 if(!live.connected||!live.daily)return state.role==='hr'?hrDashboard():dashboard();
 const allRows=live.daily.rows||[],rows=state.role==='hr'?allRows.filter(row=>String(row.employee?.employee_code||'').startsWith('HO')):allRows;
 const checkedIn=rows.filter(row=>row.first_in_at).length,notIn=rows.filter(row=>row.schedule_status==='WORK'&&!row.first_in_at).length,off=rows.filter(row=>row.schedule_status==='OFF').length,leaveCount=rows.filter(row=>['SICK_LEAVE','BUSINESS_LEAVE','VACATION','UNPAID_LEAVE'].includes(row.schedule_status)).length;
 const cards=[['เข้างานแล้ว',checkedIn,'✓','green'],['ยังไม่เข้างาน',notIn,'!','red'],['วันหยุด',off,'○','blue'],['ลา',leaveCount,'✈','amber']];
 return `<div class="hero"><div><h2>${state.role==='hr'?'ภาพรวม Head Office':'ภาพรวมวันนี้'}</h2></div><div class="date-badge"><strong>${esc(bkkDate())}</strong></div></div><div class="stats">${cards.map(card=>`<article class="stat-card"><div class="stat-top"><span>${card[0]}</span><span class="status-icon ${card[3]}">${card[2]}</span></div><strong>${card[1]}</strong></article>`).join('')}</div><section class="panel"><div class="panel-header"><h2>ข้อมูลวันนี้</h2><span class="tag green">ข้อมูลจริง · อ่านอย่างเดียว</span></div>${rows.slice(0,12).map(row=>`<div class="activity-row"><span class="status-icon ${row.first_in_at?'green':'amber'}">${row.first_in_at?'✓':'○'}</span><div><strong>${esc(row.employee?.employee_code)} · ${esc(row.employee?.name)}</strong><small>${esc(row.schedule_status||'-')}</small></div></div>`).join('')||'<p>ยังไม่มีข้อมูลวันนี้</p>'}</section>`;
}
function policyLeave(){return `<div class="page-intro"><div><h2>คำขอลา</h2></div><button class="btn pink">+ บันทึกการลา</button></div><section class="panel"><div class="tabs"><button class="tab active">รออนุมัติ · 2</button><button class="tab">อนุมัติแล้ว</button><button class="tab">ไม่อนุมัติ</button></div>${[['09','HO021 · Nan','ลาป่วย · เต็มวัน'],['12','HO007 · Ploy','ลาครึ่งวัน · ทำงานสุทธิ 4 ชั่วโมง']].map(x=>`<div class="leave-card"><div class="leave-date">${x[0]}<small>ก.ย.</small></div><div><strong>${x[1]}</strong><p>${x[2]}</p></div><span class="tag amber">รออนุมัติ</span><button class="btn primary">ตรวจสอบ</button></div>`).join('')}</section>`}
function policyReports(){const secondary=[['▦','รายงานรายวัน','ตรวจสถานะประจำวัน'],['♙','รายงานรายบุคคล','ดูประวัติรายคน'],['◫','A4 / PNG','พร้อมพิมพ์หรือบันทึกภาพ'],['◎','ภาพรวมองค์กร',state.role==='hr'?'Head Office ยกเว้น Shane และ Peet':'ดูตามกลุ่มพนักงาน']];return `<div class="reports-head"><div><h2>ศูนย์รายงาน</h2><span>เลือกช่วงเวลาแล้วเปิดดูรายละเอียด</span></div><label>เดือนรายงาน<input type="month" value="2026-09"></label></div><div class="reports-layout"><article class="report-feature"><div class="report-icon">▤</div><div><span class="report-kicker">MONTHLY SUMMARY</span><h2>รายงานรายเดือน</h2><p>ชั่วโมงทำงาน การลา เวลาชดเชย และยอดที่ฝ่ายบัญชีต้องหัก</p></div><button class="btn primary">เปิดรายงาน</button></article>${secondary.map(x=>`<article class="report-option"><div class="report-icon small">${x[0]}</div><div><h3>${x[1]}</h3><p>${x[2]}</p></div><button class="icon-button" aria-label="เปิด ${x[1]}">›</button></article>`).join('')}</div><section class="panel monthly-note"><div class="monthly-note-head"><div><span class="report-kicker">หมายเหตุในรายงาน</span><h2>ประวัติขอแก้เวลา</h2></div><span class="tag">กันยายน 2569</span></div><div class="note-table"><div class="note-row note-label"><span>ลำดับ</span><span>ผลอนุมัติ</span><span>ยอดต้องหัก</span></div>${[['ครั้งที่ 1','อนุมัติแล้ว','—',''],['ครั้งที่ 2','อนุมัติแล้ว','—',''],['ครั้งที่ 3','อนุมัติแล้ว','200 บาท','danger-row']].map(x=>`<div class="note-row ${x[3]}"><strong>${x[0]}</strong><span>${x[1]}</span><strong>${x[2]}</strong></div>`).join('')}</div><div class="compensation-note"><span class="status-icon blue">◷</span><div><strong>เวลาชดเชยใช้ได้ถึงวันทำงานถัดไป</strong><small>ยอดที่เหลือจะไม่สะสมต่อไปยังวันที่สาม</small></div></div></section>`}
function managementPage(){const items=menuByRole[state.role].filter(item=>!['dashboard','employees','schedule','reports'].includes(item[0]));return `<div class="management-head"><h2>${state.role==='admin'?'เครื่องมือ Admin':'เครื่องมือ HR'}</h2><span class="tag green">${items.length} ฟังก์ชัน</span></div><div class="management-grid">${items.map(([id,icon,label])=>`<button class="management-card" data-page="${id}"><span class="management-icon">${icon}</span><strong>${label}</strong><span class="management-arrow">›</span></button>`).join('')}</div>${state.role==='admin'?'<section class="panel parity-note"><strong>ฟังก์ชัน Admin เดิมยังอยู่ครบ</strong><span>Office, แก้เวลา, คำขอลงเวลา, การลา, LINE Report, Audit Log และตั้งค่าระบบ</span></section>':''}`}
function renderPage(){const f={dashboard:connectedDashboard,employees:employeeDirectory,schedule:interactiveSchedule,leave:policyLeave,reports:policyReports,'hr-settings':hrSettings,clock,calendar,'my-leave':policyLeave,team:employeeDirectory,line:lineReport,'clock-request':clockRequest,'clock-approvals':clockApprovals,more:managementPage};let view=f[state.page]||adminOnly;$('#content').innerHTML=view();document.querySelectorAll('#content [data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));if(state.page==='employees'&&$('#addEmployee'))$('#addEmployee').onclick=()=>{const role=$('#employeeRoleSelect');role.disabled=state.role==='hr';role.value='Employee';$('#employeeDialog').showModal()};document.querySelectorAll('[data-schedule-day]').forEach(b=>b.onclick=()=>{selectedScheduleDay=Number(b.dataset.scheduleDay);renderPage()});document.querySelectorAll('[data-personal-day]').forEach(b=>b.onclick=()=>{personalCalendar.day=Number(b.dataset.personalDay);renderPage()});document.querySelectorAll('[data-month-shift]').forEach(b=>b.onclick=()=>{personalCalendar.month+=Number(b.dataset.monthShift);if(personalCalendar.month<0){personalCalendar.month=11;personalCalendar.year--}if(personalCalendar.month>11){personalCalendar.month=0;personalCalendar.year++}personalCalendar.day=1;renderPage()});document.querySelectorAll('.preview-action,.request-submit,.approval-action').forEach(b=>b.onclick=()=>showToast('Staging เป็นโหมดอ่านอย่างเดียว — ยังไม่มีข้อมูลจริงถูกแก้ไข'))}
function setRole(role){const labels={admin:'Admin Console',hr:'HR Workspace',employee:'Employee App',ba:'BA App',driver:'Driver App'};state.role=role;$('#roleSelect').value=role;if(!['admin','hr'].includes(role))state.hrView='work';$('#workspaceSwitch').hidden=!['admin','hr'].includes(role);$('#consoleName').textContent=labels[role];if(!menuByRole[role].some(x=>x[0]===state.page))state.page=['employee','ba','driver'].includes(role)?'clock':'dashboard';syncHrSwitch();go(state.page)}
function syncHrSwitch(){document.querySelectorAll('[data-hr-view]').forEach(b=>b.classList.toggle('active',b.dataset.hrView===state.hrView));if(['admin','hr'].includes(state.role)){const personal=state.hrView==='personal',isAdmin=state.role==='admin';document.querySelector('[data-hr-view="work"]').textContent=isAdmin?'งาน Admin':'งาน HR';$('#consoleName').textContent=personal?'My Attendance':(isAdmin?'Admin Console':'HR Workspace')}}
document.querySelectorAll('[data-hr-view]').forEach(b=>b.onclick=()=>{state.hrView=b.dataset.hrView;state.page=state.hrView==='personal'?'clock':'dashboard';syncHrSwitch();go(state.page)});
$('#roleSelect').onchange=e=>setRole(e.target.value);
$('#employeeForm').onsubmit=e=>{e.preventDefault();$('#employeeDialog').close();$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),3000)};
function showToast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),3000)}
function openAction(label){const templates={
 'ดูทั้งหมด':['รายการความเคลื่อนไหว','<div class="action-list"><p><strong>13:42 · HO018</strong><span>เข้างาน · Head Office</span></p><p><strong>13:10 · BA012</strong><span>เริ่มงาน · Siam Paragon</span></p><p><strong>12:58 · HO021</strong><span>เข้าพัก · Head Office</span></p></div>'],
 'ดูข้อมูล':['ข้อมูลพนักงาน','<div class="action-summary"><span class="avatar">DT</span><div><h3>HO018 · Don Thanakorn</h3><p>Employee · Head Office</p></div></div><div class="form-grid"><label>สำนักงาน<input value="Head Office" readonly></label><label>วันหยุด<input value="เสาร์, อาทิตย์" readonly></label></div>'],
 'แก้ไข':['แก้ไขข้อมูล','<div class="form-grid"><label>ชื่อพนักงาน<input value="Don Thanakorn"></label><label>บทบาท<select><option>Employee</option><option>HR</option><option>BA</option><option>Driver</option></select></label><label>สำนักงาน<select><option>Head Office</option><option>Siam Paragon</option><option>Central World</option></select></label><label>สถานะ<select><option>Active</option><option>Inactive</option></select></label></div><p class="logic-note">Admin สามารถตั้งบทบาทได้ · HR ไม่สามารถเปลี่ยนบทบาทสำคัญ</p>'],
 'ตรวจสอบ':['ตรวจสอบคำขอลา','<div class="action-summary"><span class="avatar">NN</span><div><h3>HO021 · Nan Nicha</h3><p>ลาป่วย · 9 กันยายน · 1 วัน</p></div></div><label class="action-field">หมายเหตุ<textarea rows="3" placeholder="หมายเหตุผู้อนุมัติ"></textarea></label>'],
 'เปิดรายงาน →':['ตัวอย่างรายงาน','<div class="line-preview"><strong>รายงานประจำวัน · Head Office</strong><p>เข้างานแล้ว 8 คน</p><p>ยังไม่เข้างาน 2 คน</p><p>ลา 1 คน · WFH 1 คน</p></div>'],
 'ดูรายละเอียด':['รายละเอียดตารางงาน','<div class="action-summary"><span class="avatar">DT</span><div><h3>HO018 · Don Thanakorn</h3><p>WORK · 09:00–18:00 · Head Office</p></div></div><div class="timeline-mini"><span>09:02 เข้างาน</span><span>12:10 ออกพัก</span><span>13:01 เข้าพัก</span><span>— รอออกงาน</span></div>'],
 'เข้างาน':['ยืนยันเข้างาน','<div class="confirm-card"><strong>13:55 น.</strong><p>Kitty Kawaii Head Office · ระยะห่าง 34 เมตร</p></div>'],
 'ออกงาน':['ยืนยันออกงาน','<div class="confirm-card"><strong>13:55 น.</strong><p>ระบบจะแสดงสรุปชั่วโมงทำงานก่อนยืนยัน</p></div>'],
 'ออกพัก':['ยืนยันออกพัก','<div class="confirm-card"><strong>13:55 น.</strong><p>เริ่มจับเวลาพักหลังยืนยัน</p></div>'],
 'เข้าพัก':['ยืนยันกลับจากพัก','<div class="confirm-card"><strong>13:55 น.</strong><p>สิ้นสุดเวลาพักหลังยืนยัน</p></div>']};
 if(label==='แก้ไข'&&state.role==='hr')templates[label]=['แก้ไขข้อมูล','<div class="form-grid"><label>ชื่อพนักงาน<input value="Don Thanakorn"></label><label>สำนักงาน<input value="Head Office" readonly></label><label>สถานะ<select><option>Active</option><option>Inactive</option></select></label></div><p class="logic-note">HR แก้ข้อมูลพนักงาน Head Office ได้ แต่ไม่สามารถเปลี่ยนบทบาท</p>'];const [title,body]=templates[label]||[label,`<div class="restricted"><strong>ตัวอย่างขั้นตอน ${label}</strong><p>หน้าจอนี้แสดงผลลัพธ์ที่ผู้ใช้จะเห็น โดยยังไม่บันทึกหรือส่งข้อมูลจริง</p></div>`];$('#actionTitle').textContent=title;$('#actionBody').innerHTML=body;$('#confirmActionDialog').textContent=label.includes('ดู')||label.includes('รายงาน')?'ปิด':'ยืนยันใน Preview';$('#actionDialog').showModal()}
$('#closeActionDialog').onclick=$('#cancelActionDialog').onclick=()=>$('#actionDialog').close();$('#confirmActionDialog').onclick=()=>{$('#actionDialog').close();showToast('ดำเนินการใน Preview สำเร็จ — ไม่มีข้อมูลจริงถูกเปลี่ยน')};
document.addEventListener('click',e=>{
 const button=e.target.closest('button');if(!button||button.dataset.page||button.dataset.hrView||button.dataset.personalDay||button.dataset.monthShift||button.closest('dialog'))return;
 if(button.classList.contains('tab')){button.parentElement.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));button.classList.add('active');showToast(`เปลี่ยนเป็นแท็บ “${button.textContent.trim()}” ใน Preview แล้ว`);return}
 if(button.classList.contains('request-submit')||button.classList.contains('approval-action')||button.classList.contains('preview-action'))return;
 openAction(button.textContent.trim()||'รายการนี้');
});
document.addEventListener('click',e=>{const card=e.target.closest('.stat-card');if(card)openAction(card.querySelector('.stat-top span').textContent)})
setRole('employee');
initLive();
